### ISSUE TITLE
Usage with non-gaussian distributions

### ISSUE THREAD

**Issue by brenolf** [joluet/okde-java#1]
I have tried the example provided and changed the random gaussian distribution to one in which all values are the same. This change makes the example crash with the error `MatrixDimensionException: The 'a' and 'b' matrices do not have compatible dimensions` triggered by a `mult` call on `projectToSubspace`. 

Are there any limitations on what distributions one can use with this library?

**Comment by brenolf** [comment]
Actually it seems that I cannot call `updateDistribution` on repeated values (I tried a random Poisson distribution and it worked, but it didn't for a constant distribution), nor can I start with an empty distribution and update my distribution using a single document (if I try it, then I get `MatrixDimensionException: A and B are not compatible`). 

I tried initializing the distribution with some samples from the Iris database, for instance, and I have not been able to properly create it, since a `MatrixDimensionException: A and B are not compatible` is thrown when `updateDistribution` is called on previously seen values (which happens frequently in real-world datasets). Maybe I'm just missing something that is not documented.

**Comment by joluet** [comment]
Sorry about the cryptic unhandled exception. I haven't actively worked on this project in a while. 

The error you see occurs because a distribution initialized from equal samples is underconstrained so the variance is zero. Meaning that you cannot estimate a distribution from this. Unfortunately my implementation doesn't handle this case and just crashes when the estimation failts. It should probably handle this issue differently.

**Comment by brenolf** [comment]
My use-case requires 1-sample online training. Thus, starting with 2 random training samples might end up having same-valued attributes.

It does make sense not to estimate a function, if the training points are drawn from a degenerate distribution. I "fixed" the problem by adding a small gaussian noise to the input.
